model-training:

  runs-on: ubuntu-latest

  needs: data-prep

  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download train and test datasets
      uses: actions/download-artifact@v4
      with:
        name: data-splits
        path: tourism_project/data

    - name: Verify downloaded datasets
      run: |
        echo "Downloaded datasets:"
        ls -lh tourism_project/data

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn mlflow joblib

    - name: Run model training
      run: |
        python tourism_project/model_building/model_train.py

    - name: Verify saved model
      run: |
        echo "Model files:"
        ls -lh tourism_project/model_building/

    - name: Upload MLflow tracking
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-tracking
        path: mlruns/

    - name: Commit best model
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add tourism_project/model_building/best_model.joblib

        if git diff --cached --quiet; then
          echo "No model changes to commit."
        else
          git commit -m "Update best model"
          git push
        fi
